[package]
name = "chipioindustries/live-debug-toolkit"
description = "Framework for loading GUI debug tools."
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["wally.exe"]

[dependencies]
makeStandalone = "chipioindustries/make-standalone@1.0.5"
Signal = "chipioindustries/signal@1.1.1"
Remotes = "chipioindustries/remotes@1.0.6"
Roact = "roblox/roact@1.4.4"
RoactHooks = "kampfkarren/roact-hooks@0.5.0"
RoactRodux = "roblox/roact-rodux@0.3.0"
t = "osyrisrblx/t@3.0.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"