[package]
name = "chipioindustries/live-debug-toolkit"
description = "Framework for loading GUI debug tools."
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["wally.exe"]

[dependencies]
makeStandalone = "chipioindustries/make-standalone@1.0.5"
Signal = "chipioindustries/signal@1.1.1"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"